### ISSUE TITLE
Create continer failed due to DVDI_VOLUME_NAME is not valid

### ISSUE THREAD

**Issue by gyliu513** [emccode/mesos-module-dvdi#81]
I was using 0.27.0 dvd driver and the env json is as following:
root@mesos002:~/src/mesos/27/mesos/build# cat /opt/env.json
{
  "DVDI_VOLUME_NAME": "123",
  "DVDI_VOLUME_DRIVER": "convoy"
}

I was always getting this error when launch a task
E0314 20:17:41.391485  2008 docker_volume_driver_isolator.cpp:485] Environment variable DVDI_VOLUME_NAME rejected because it's value contains prohibited characters

**Comment by cantbewong** [comment]
the checking is there to prevent injection attacks, and perhaps is too
strict I realized when I put it in that it restricts the character set to
and in particular probably prohibits non-English characters.

The fear was that some organizations enable non admin access to the
Marathon UI, and since the isolator invokes the DVDCLI as root, an
injection attack is theoretically possible.

I will be adding to the document, and one of my proposals is to remove the
check, or move the implementation to a place outside the isolator

I believe that Mesos in general already has this exposure to injection
attack in places, for example I think the containerization may invoke a
command line command as root - so when moving this into Mesos, it would be
no worse than code that is already there. And if this worries somebody it
would be better to put the protection on the exec function and protect
everything in one place. Thus my proposal to remove the checking.

BTW I might not put this detail about the injection attack risk in the
public document.

For non-open-source software it is the EMC policy to avoid publishing
security exposures. We don't have any official policy for open source, but
I think t may be prudent to avoid publishing this until a fix is in place

**Comment by cantbewong** [comment]
I tested this using the RexRay volume driver and had no issues when using a volume name of "123"

**Comment by gyliu513** [comment]
Thanks @cantbewong I think that we can close this now.
